### ISSUE TITLE
[ tests ] Fix Failing tests

### ISSUE THREAD

**Issue by inishchith** [chaoss/grimoirelab-graal#3]
[Reference](https://travis-ci.org/inishchith/graal/jobs/497318087)

@jgbarah @valeriocos I'd like to work on this issue. Please let me know if this is already being worked on 😄

**Comment by valeriocos** [comment]
Thank you @inishchith, sure you can.

I guess CI tests fail because the libraries used (e.g., nomossa, scancode) are not copied where the tests are executed. Thus some work is needed on the [travis.yml](https://github.com/chaoss/grimoirelab-graal/blob/master/.travis.yml) to upload these libraries.

There are also some minor issues related the badges due to the recent transfer of the repo. In the [README.md](https://github.com/chaoss/grimoirelab-graal/blob/master/README.md), the markdowns of the badges should be changed to:

**travis**
```
[![Build Status](https://travis-ci.org/grimoirelab-graal.svg?branch=master)](https://travis-ci.org/chaoss/grimoirelab-graal)
```

**coveralls**
```
[![Coverage Status](https://coveralls.io/repos/github/chaoss/grimoirelab-graal/badge.svg?branch=master)](https://coveralls.io/github/chaoss/grimoirelab-graal?branch=master)
```

Hope this info helps you.

**Comment by inishchith** [comment]
@valeriocos Thanks for the help. I've opened a PR with a fix for this and also updating the `README.md`. Please do have a look and let me know if any changes required 😅
